require("core.remap")
require("core.lazy")
require("core.options")
-- require("core.relative-toggle")
require("core.neovide-options")
require("core.mode-recolor")
require("core.highlights")
-- require("core.grapple-line")
-- require("core.autocwd")
