require("core.neovide-options")
require("core.remap")
require("core.lazy")
require("core.options")
-- require("core.relative-toggle")
require("core.mode-recolor")
require("core.highlights")
require("core.gdscript")
require("core.session")
require("lsp.lsp")
-- require("core.grapple-line")
-- require("core.autocwd")

require("utils.treesitter")
